const express = require("express");
const router = express.Router();
const tiendaController = require("../controllers/tiendaController");
router.get("/RecuperarGeneros", tiendaController.recuperarGeneros);
router.get("/RecuperarAlbumes", tiendaController.recuperarAlbumes);
router.get("/RecuperarAlbumesGenero/:genero", tiendaController.recuperarAlbumesGenero);
router.get("/RecuperarAlbumesArtista/:artista", tiendaController.recuperarAlbumesArtista);
router.get("/RecuperarAlbum/:id", tiendaController.recuperarAlbum);
router.get("/RecuperarComentariosAlbum/:id", tiendaController.recuperarComentariosAlbum);
router.post("/InsertarComentarioAlbum", tiendaController.insertarComentarioAlbum);
router.get("/BuscarAlbumes/:busqueda", tiendaController.buscarAlbumes);
module.exports = router;